# Basic stuff
title: James Bornholt
description: >
  I'm an assistant professor in the Department of Computer Science
  at the University of Texas at Austin, working on programming languages and formal methods.

# URLs
baseurl: "/~bornholt"
url: "https://www.cs.utexas.edu"
permalink: /post/:title.html

# Version
css_version: 20200803


# Markdown settings
markdown: kramdown
kramdown:
  input: GFM


# Build settings
exclude:
  - Gemfile
  - Gemfile.lock
  - Makefile
  - README.md


# Default layout
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
